// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Quiz.Domain.Infra.Contexts;

namespace Quiz.Domain.Infra.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Quiz.Domain.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnswerA")
                        .HasColumnType("varchar(80)")
                        .HasMaxLength(80);

                    b.Property<string>("AnswerB")
                        .HasColumnType("varchar(80)")
                        .HasMaxLength(80);

                    b.Property<string>("AnswerC")
                        .HasColumnType("varchar(80)")
                        .HasMaxLength(80);

                    b.Property<string>("AnswerD")
                        .HasColumnType("varchar(80)")
                        .HasMaxLength(80);

                    b.Property<string>("Company")
                        .HasColumnType("varchar(80)")
                        .HasMaxLength(80);

                    b.Property<string>("CorrectAnswer")
                        .HasColumnType("varchar(80)")
                        .HasMaxLength(80);

                    b.Property<string>("Title")
                        .HasColumnType("varchar(160)")
                        .HasMaxLength(160);

                    b.HasKey("Id");

                    b.ToTable("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
